
apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: echo-pod  
spec:  
  selector:  
    matchLabels:  
      app: echo-pod
  replicas: 3  
  template:  
    metadata:  
      labels:  
        app: echo-pod  
    spec:  
      containers:  
      - name: echo-pod  
        image: httpd:2.4  
        ports:  
        - containerPort: 80  